CREATE TABLE IF NOT EXISTS spending (
    id SERIAL PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    category VARCHAR(50),
    date DATE DEFAULT CURRENT_DATE
);